on: [push]

#name: ARM build
name: msvc rust

jobs:
  windows:
    name: windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ilammy/msvc-dev-cmd@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Build
        env:
          RUSTFLAGS: -C target-cpu=amdfam10 #-Cprofile-generate=pgodata -Cpanic=abort
        run: 
          cargo build --release

      - uses: actions/upload-artifact@v2
        with:
          name: trojan-r.exe
          path: target/release/trojan-r.exe
          

  android:
    name: android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: aarch64-linux-android
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          env: 
            RUSTFLAGS='-C target-cpu=cortex-a53'
          command: build
          args: --release --target aarch64-linux-android
      - uses: actions/upload-artifact@v2
        with:
           name: android-trojan-r
           path: target/aarch64-linux-android/release/trojan-r

  mipsel:
    name: mipsel
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: mipsel-unknown-linux-gnu
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: list
          #args: --release --target mipsel-unknown-linux-gnu

      - uses: actions/checkout@v2
        with:
          repository: 'https://github.com/briansmith/ring.git'
          run: 
            git fetch origin pull/1181/head:mips
            git checkout mips

      - uses: P3TERX/ssh2actions@v1.0.0

      - uses: actions/upload-artifact@v2
        with:
           name: mips-trojan-r
           path: target/mipsel-unknown-linux-gnu/release/trojan-r
  
  linux:
    name: linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          env: 
            RUSTFLAGS='-C target-cpu=cascadelake'
          command: build
          args: --release
      - uses: actions/upload-artifact@v2
        with:
           name: linux-trojan-r
           path: target/release/trojan-r

