on: [push]

#name: ARM build
name: msvc rust

jobs:
  windows:
    name: windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ilammy/msvc-dev-cmd@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Build
        env:
          RUSTFLAGS: -C target-cpu=amdfam10 #-Cprofile-generate=pgodata -Cpanic=abort
        run: 
          cargo build --release

      - uses: actions/upload-artifact@v2
        with:
          name: trojan-r.exe
          path: target/release/trojan-r.exe
          

  android:
    name: android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: aarch64-linux-android
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          env: 
            RUSTFLAGS='-C target-cpu=cortex-a53'
          command: build
          args: --release --target aarch64-linux-android
      - uses: actions/upload-artifact@v2
        with:
           name: android-trojan-r
           path: target/aarch64-linux-android/release/trojan-r

  mipsel:
    name: mipsel
    runs-on: ubuntu-latest
    steps:
      - name: Checkout trojan-r
        uses: actions/checkout@v2
        
      - name: Checkout ring
        uses: actions/checkout@v2
        with:
          repository: 'briansmith/ring'
          path: './ring'

      - name: Checkout ring PR 1181 with mips support
        working-directory: ./ring
        run: |
          git fetch origin pull/1181/head:mips
          git checkout mips
      
      - name: Patch Cargo.toml
        run: |
          echo '[patch.crates-io]' >> Cargo.toml
          echo 'ring = { path = "./ring" , version = "0.16.19" }' >> Cargo.toml

      - uses: P3TERX/ssh2actions@v1.0.0
      
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: mipsel-unknown-linux-musl
          override: true
    
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          env:
            RUSTFLAGS='-C target-cpu=mips32r2'
          args: --release --target mipsel-unknown-linux-musl

      - uses: actions/upload-artifact@v2
        with:
           name: mips-trojan-r
           path: target/mipsel-unknown-linux-musl/release/trojan-r
  
  linux:
    name: linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          env: 
            RUSTFLAGS='-C target-cpu=cascadelake'
          command: build
          args: --release
      - uses: actions/upload-artifact@v2
        with:
           name: linux-trojan-r
           path: target/release/trojan-r

